title: Túrajegyzetek
description: Rövid jegyzetek túrákról, útvonalakról, helyekről és személyes tapasztalatokról.
lang: hu
theme: minima
markdown: kramdown

plugins:
  - jekyll-feed

baseurl: "/TravelNotes"
url: "https://lguba71.github.io"

include:
  - assets
