title: Travel Notes
description: Short notes from routes, places, and trips.
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

baseurl: "/TravelNotes"
url: "https://lguba71.github.io"

css:
  - /assets/css/custom.css
